### ISSUE TITLE
Stuck on logo Apple

### ISSUE THREAD

**Issue by farhannovan** [mvinicius-mvss/EFI-NOTEBOOK-LENOVO-IDEIAPAD-310-14ISK#1]
Hi, I want to ask, is this EFI successful on your laptop? the problem is on my laptop the first time it boot it get stuck on the apple logo. Thanks in advance :)

**Comment by mvinicius-mvss** [comment]
Yes, it is working normally on my laptop. Is yours the same model as mine? It only works on the same model. ideapad 310 14-isk
You need to make some changes to the config.plist to be able to see where the error is.
my discord Marcos Vinicius#3344

**Comment by farhannovan** [comment]
yes, the same model maybe need a little modification, I will try next time. Thank you
